logging:
  level:
    org.springframework.web.servlet: info
    org.springframework.web: info
    org.springframework.boot: info
    org.springframework.data.redis: info
    org.springframework.data.mongodb.core.MongoTemplate: info
    com.hsik.smoking: info

server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 10500
  shutdown: graceful

spring:
  docker:
    compose:
      lifecycle-management: start_only

  output:
    ansi:
      enabled: always
  data:
    mongodb:
      auto-index-creation: true

    redis:
      timeout: 3000ms
      connect-timeout: 3000ms

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: false

app:
  open-data-portal:
    host: https://api.odcloud.kr
    use-dummy: false

  kakao:
    host: https://dapi.kakao.com
    use-dummy: false
